/**
   *  Value class to hold user's Territory hierarchy structure
   */
global  class TerritoryHierarchy{
      //TBM
      public String TBMcode {get{return TBMcode; } set{TBMcode = value;}}
      public String TBMID {get{return TBMID; } set{TBMID = value;}}
      public string TBMdesc {get{return TBMdesc; } set{TBMdesc = value;}}
      public string TBMuser {get{return TBMuser; } set{TBMuser = value;}}
      //RBM
      public String RBMcode {get{return RBMcode; } set{RBMcode = value;}}
      public String RBMID {get{return RBMID; } set{RBMID = value;}}
      public string RBMdesc {get{return RBMdesc; } set{RBMdesc = value;}}
      public string RBMuser {get{return RBMuser; } set{RBMuser = value;}}
      //AVP
      public String AVPcode {get{return AVPcode; } set{AVPcode = value;}}
      public String AVPID {get{return AVPID; } set{AVPID = value;}}
      public string AVPdesc {get{return AVPdesc; } set{AVPdesc = value;}}
      public string AVPuser {get{return AVPuser; } set{AVPuser = value;}}
	
  }